### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by MHammett** [chuckleplant/blog#1]
C:\Users\mhammett\Downloads>C:\Users\mhammett\AppData\Local\Programs\Python\Python37\python.exe location-geotag.py --dir ..\Pictures\2019-06-09 --json "takeout-20190610T030953Z-001\Takeout\Location History\Location History.json"
  File "location-geotag.py", line 74
    print datetime.datetime.fromtimestamp(epoch_time).strftime("%Y:%m:%d %H:%M:%S")
                 ^
SyntaxError: invalid syntax

C:\Users\mhammett\Downloads>c:\Python27\python.exe location-geotag.py --dir ..\Pictures\2019-06-09 --json "takeout-20190610T030953Z-001\Takeout\Location History\Location History.json"
Traceback (most recent call last):
  File "location-geotag.py", line 17, in <module>
    from PIL import Image
ImportError: No module named PIL

**Comment by MHammett** [comment]
Okay, I had to run `c:\Python27\python -m pip install --upgrade pip` to fix PIL. Now I'm on to pexif. 

c:\Python27\python -m pip install pexif

c:\Python27\python -m pip install piexif

**Comment by chuckleplant** [comment]
Hi there! Sorry I just saw this, yep you'll need to install all dependencies. Let me know if you find other issues.
